/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "npuzevvrqeivqpwdripy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdXpldnZycWVpdnFwd2RyaXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NDAzNzQsImV4cCI6MjA3OTIxNjM3NH0.LH33RMasKH-XViohs0wj20r-yNBNQwKB2f6suouHxr4"